name: "Push to Feature Branch"
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!develop'
      - '!stage'
      - '!main'

jobs:
  validate-build:
    permissions: #Permission is required if enabling TFSEC == true
      actions: read
      contents: read
      security-events: write
    uses: linh5847/aws-terraform-github-action-cicd/.github/workflows/az_tf_plan.yml@8b035d2e70696e4a080e573f8f82d2a3a9621cbd # Required a first feature branch git ref
    with:
      path: dev ## Path to terraform root module (Required)
      enable_TFSEC: true ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} ## AWS_ACCESS_KEY_ID
      aws_secret_access_key: ${{ secrets.DEV_ARM_CLIENT_SECRET }} ## AWS_SECRET_ACCESS_KEY
      aws_default_region: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }} ## AWS_DEFAULT_REGION
